name: Build and Push Docker Image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: mysubdir  # Adjust this as needed
          push: true
          tags: thaumaturgists/canamu:latest  # Replace with your actual Docker Hub username and repo

      - name: Run Tests (Optional)
        if: ${{ github.event_name == 'push' }}
        run: |
          docker run --rm thaumaturgists/canamu:latest npm test
